variable "region" {}
variable "username" {}
variable "state_bucket" {}
variable "table_name" {}
variable "company_name" {}
variable "vpc_cidr" {}
variable "public_subnet_1" {}
variable "public_subnet_2" {}
variable "private_subnet_1" {}
variable "private_subnet_2" {}