variable "region" {}
variable "az1" {}
variable "az2" {}
variable "username" {}
variable "state_bucket" {}
variable "table_name" {}
variable "vpc_cidr" {}
variable "public_subnet_1" {}
variable "public_subnet_2" {}
variable "private_subnet_1" {}
variable "private_subnet_2" {}
variable "ami" {}
variable "instance_type" {}
variable "key_name" {}
variable "instance_class" {}
variable "db_username" {}
variable "db_password" {}
variable "engine_version" {}
