name: Terraform Infrastructure Deployment
on:
  push:
    branches:
      - main

jobs: 
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest    

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        #Script to create my TF.vars file and keep mine out the repo
      - name: Create terraform.tfvars
        run: |
          cat << EOF > terraform.tfvars
          username = "2tier_user"
          state_bucket = "2tier-state-bucket-runsabba"
          table_name = "2tier-state-lock-table"
          region = "us-east-1"
          az1 = "us-east-1a"
          az2 = "us-east-1b"
          vpc_cidr = "10.0.0.0/16"
          public_subnet_1 = "10.0.0.0/18"
          public_subnet_2 = "10.0.64.0/18"
          private_subnet_1 = "10.0.128.0/18"
          private_subnet_2 = "10.0.192.0/18"
          ami = "ami-0e86e20dae9224db8"
          instance_type = "t2.micro"
          key_name = "${{ secrets.TF_VAR_KEY_NAME }}"
          instance_class = "db.t3.micro"
          db_username = "${{ secrets.TF_VAR_DB_USER }}"
          db_password = "${{ secrets.TF_VAR_DB_PASSWORD }}"
          engine_version = "5.7.44"
          EOF

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      #- name: Terraform Apply
        ##if:github.ref == 'refs/heads/main' && github.event_name == 'push'
        #run: terraform apply -auto-approve tfplan


#after 21 failures we got it!!!